name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # Save the
 

jobs:
  build:
    runs-on: self-hosted
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Override HOME environment variable
      run: |
        pwd
        ls
        #export HOME='/home/ec2-user/actions-runner/aap/BidonBuy-Client/actions-runner/_work/_temp/a61c01f5-d846-44f6-8719-638e9e420972'      
   
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Install dependencies
      run: |
       #sudo yum -y install curl
       
       #curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
       sudo yum -y install nodejs npm
      
    - name: Run tests
      run: |
       sudo yum install nginx -y
       sudo yum -y install nodejs npm
       sudo npm install --force
       sudo npm i react-password-strength-bar --force

       sudo npm run build
       sudo cp -rf build/* /usr/share/nginx/html/
       sudo systemctl start nginx
       
